name: babylon_dart
description: Dart bindings for the BabylonJS 4.2 rendering engine for the web.
version: 1.0.0-nullsafety.1
homepage: https://www.github.com/blimster/babylon_dart

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dependencies:
    js: ^0.6.3-nullsafety

dev_dependencies:
    build_runner: ^1.10.0
    build_web_compilers: ^2.7.0
    pedantic: ^1.9.0
