name: babylon_dart
description: Dart bindings for the BabylonJS 4.2 rendering engine for the web.
version: 1.1.1
homepage: https://www.github.com/blimster/babylon_dart

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    js: ^0.6.3

dev_dependencies:
    build_runner: ^2.1.4
    build_web_compilers: ^3.2.1
    pedantic: ^1.9.0
