part of babylon;

/// interface IMaterialSheenDefines
@JS()
abstract class IMaterialSheenDefines {
  bool SHEEN;
  bool SHEEN_TEXTURE;
  bool SHEEN_TEXTURE_ROUGHNESS;
  num SHEEN_TEXTUREDIRECTUV;
  num SHEEN_TEXTURE_ROUGHNESSDIRECTUV;
  bool SHEEN_LINKWITHALBEDO;
  bool SHEEN_ROUGHNESS;
  bool SHEEN_ALBEDOSCALING;
  bool SHEEN_USE_ROUGHNESS_FROM_MAINTEXTURE;
  bool SHEEN_TEXTURE_ROUGHNESS_IDENTICAL;
}
