part of babylon;

/// interface IMaterialClearCoatDefines
@JS()
abstract class IMaterialClearCoatDefines {
  bool CLEARCOAT;
  bool CLEARCOAT_DEFAULTIOR;
  bool CLEARCOAT_TEXTURE;
  bool CLEARCOAT_TEXTURE_ROUGHNESS;
  num CLEARCOAT_TEXTUREDIRECTUV;
  num CLEARCOAT_TEXTURE_ROUGHNESSDIRECTUV;
  bool CLEARCOAT_BUMP;
  num CLEARCOAT_BUMPDIRECTUV;
  bool CLEARCOAT_USE_ROUGHNESS_FROM_MAINTEXTURE;
  bool CLEARCOAT_TEXTURE_ROUGHNESS_IDENTICAL;
  bool CLEARCOAT_REMAP_F0;
  bool CLEARCOAT_TINT;
  bool CLEARCOAT_TINT_TEXTURE;
  num CLEARCOAT_TINT_TEXTUREDIRECTUV;
}
