part of babylon;

/// interface IMaterialSubSurfaceDefines
@JS()
abstract class IMaterialSubSurfaceDefines {
  bool SUBSURFACE;
  bool SS_REFRACTION;
  bool SS_TRANSLUCENCY;
  bool SS_SCATTERING;
  bool SS_THICKNESSANDMASK_TEXTURE;
  num SS_THICKNESSANDMASK_TEXTUREDIRECTUV;
  bool SS_REFRACTIONMAP_3D;
  bool SS_REFRACTIONMAP_OPPOSITEZ;
  bool SS_LODINREFRACTIONALPHA;
  bool SS_GAMMAREFRACTION;
  bool SS_RGBDREFRACTION;
  bool SS_LINEARSPECULARREFRACTION;
  bool SS_LINKREFRACTIONTOTRANSPARENCY;
  bool SS_ALBEDOFORREFRACTIONTINT;
  bool SS_MASK_FROM_THICKNESS_TEXTURE;
  bool SS_MASK_FROM_THICKNESS_TEXTURE_GLTF;
}
